# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06bdc7f1efbf89d34e94eae2676b27dd002c37ddc84df77cd82089755c3141daa1a168f7c527f067169b6ba71adcba15f8f34433bfc9b70981309de9b5bcc34c

test:
  secret_key_base: 959d9b6316dc90a57cfe3ec93a6c58ee720a74290c0b50c5f542d63e45be6d59f890750c0cb584acf6afee42e2ad374ec70bc99b328e9bec8d0289cf4c672bff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
